baseURL = "https://Sainsdansejarah.github.io/zonasenyap-docs/"
title = "Sains dan Sejarah"
theme = "zonasenyap"
defaultContentLanguage = "id"

[languages]
[languages.id]
  locale = "id_ID"

[params]
  description = "Dokumentasi edukatif tentang sains, teknologi, sejarah dunia, peradaban, tokoh berpengaruh, penemuan, dan peristiwa penting."
  author = "Zona Senyap"
  
[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNos = false
    lineNumbersInTable = false
    noClasses = true
    style = 'monokai'
    tabWidth = 4
